### ISSUE TITLE
As an authenticated user, I can answer a question

### ISSUE THREAD

**Issue by alexstojda** [alexstojda/SOEN341#19]
A user can answer a question, including his own.

**Comment by alexstojda** [comment]
@PeterGhimself the backend is done. So just need you to make the front end. 
Form should post to `/answer/{id}` where {id} is the id of the question to be answered. 
Only field that needs to be sent is `body`. See how @niconoloco implemented the question form for help.

**Comment by niconoloco** [comment]
3 Changes that need to be done for this commit to be preceded.
1. We need a show method(inside AnswersController with its own route) that returns answers from database. This is so we can display them on questions page.
2. In comment model question id and author id need to be fillable and in the store method
they must be required or else they won't save to DB.
3. The construst method in the AnswersController doesnt need except Index and show since you dont have index and show methods(unless you're planning to make them).

**Comment by alexstojda** [comment]
@niconoloco you wrote "in comment model" for Number 2, did you mean for answers model?

**Comment by niconoloco** [comment]
Yes absolutely “Answer model”

**Comment by alexstojda** [comment]
Also, are you sure that author_id needs to be fillable? as in the question model you wrote author_id is not fillable.

**Comment by alexstojda** [comment]
@niconoloco Please review the latest commits.

**Comment by niconoloco** [comment]
In the question and answer model fillable must include author_id. My bad for not having it in question model.
Besides that all other changes are good.

**Comment by Evi1NoOb** [comment]
[#49] i need a working version of answers and the database updated to be able to add voting to them.
@niconoloco

**Comment by alexstojda** [comment]
@niconoloco Mind making that adjustment? I'm afk at the moment
________________________________
